### ISSUE TITLE
Transfer ownership

### ISSUE THREAD

**Issue by isaacabraham** [Akash-Mair/feliz-react-awesome-slider#1]
Hey @Akash-Mair would you mind transferring ownership of this to the CIT org? We're doing a sweep of upgrades to SAFE packages that we've built and this one is under your ownership at the moment.

Thanks :-)

**Comment by mattgallagher92** [comment]
Done!

**Comment by mattgallagher92** [comment]
Thanks @Akash-Mair :heart:
